from __future__ import annotations

from typing import Dict, List, Optional

DEMO_PRODUCTS: List[Dict] = [
    # TOPS
    {
        "item_id": "T01",
        "category": "Top",
        "item_name": "Oversized Linen Shirt",
        "price": 899.0,
        "rating": 4.8,
        "reviews": 128,
        "platform": "Myntra",
        "colour": "Navy Blue",
        "shade": "Navy",
        "style": "Casual",
        "occasion": "College",
        "fabric": "Linen",
        "fabric_tag": "Breathable Linen",
        "image": "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=400&q=80",
    },
    {
        "item_id": "T02",
        "category": "Top",
        "item_name": "Tailored Oxford Shirt",
        "price": 1299.0,
        "rating": 4.9,
        "reviews": 210,
        "platform": "ZARA",
        "colour": "White",
        "shade": "Ivory",
        "style": "Formal",
        "occasion": "Office",
        "fabric": "Cotton Blend",
        "fabric_tag": "Crisp Cotton",
        "image": "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=400&q=80",
    },
    {
        "item_id": "T03",
        "category": "Top",
        "item_name": "Satin Wrap Blouse",
        "price": 1499.0,
        "rating": 4.7,
        "reviews": 95,
        "platform": "H&M",
        "colour": "Burgundy",
        "shade": "Maroon",
        "style": "Trendy",
        "occasion": "Party",
        "fabric": "Silk Satin",
        "fabric_tag": "Lustrous Silk",
        "image": "https://images.unsplash.com/photo-1564257631407-4deb1f99d992?auto=format&fit=crop&w=400&q=80",
    },
    {
        "item_id": "T04",
        "category": "Top",
        "item_name": "Embroidered Kurti",
        "price": 1199.0,
        "rating": 4.8,
        "reviews": 310,
        "platform": "FabIndia",
        "colour": "Mustard Yellow",
        "shade": "Mustard",
        "style": "Ethnic",
        "occasion": "Traditional Event",
        "fabric": "Khadi Cotton",
        "fabric_tag": "Handloom Khadi",
        "image": "https://images.unsplash.com/photo-1583391733956-6c78276477e2?auto=format&fit=crop&w=400&q=80",
    },
    {
        "item_id": "T05",
        "category": "Top",
        "item_name": "Minimalist Crewneck Tee",
        "price": 499.0,
        "rating": 4.6,
        "reviews": 540,
        "platform": "UNIQLO",
        "colour": "Beige",
        "shade": "Sand",
        "style": "Minimal",
        "occasion": "Casual Outing",
        "fabric": "Supima Cotton",
        "fabric_tag": "Soft Cotton",
        "image": "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=400&q=80",
    },
    {
        "item_id": "T06",
        "category": "Top",
        "item_name": "Structured Blazer",
        "price": 2499.0,
        "rating": 4.9,
        "reviews": 180,
        "platform": "Mango",
        "colour": "Olive Green",
        "shade": "Olive",
        "style": "Smart Casual",
        "occasion": "Interview",
        "fabric": "Wool Blend",
        "fabric_tag": "Structured Wool",
        "image": "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=400&q=80",
    },

    # BOTTOMS
    {
        "item_id": "B01",
        "category": "Bottom",
        "item_name": "Relaxed Straight Denim",
        "price": 1199.0,
        "rating": 4.8,
        "reviews": 420,
        "platform": "Levi's",
        "colour": "Classic Blue",
        "shade": "Denim",
        "style": "Casual",
        "occasion": "College",
        "fabric": "Denim",
        "fabric_tag": "Durable Denim",
        "image": "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=400&q=80",
    },
    {
        "item_id": "B02",
        "category": "Bottom",
        "item_name": "Slim Fit Chino Trousers",
        "price": 1399.0,
        "rating": 4.7,
        "reviews": 165,
        "platform": "UNIQLO",
        "colour": "Beige",
        "shade": "Khaki",
        "style": "Smart Casual",
        "occasion": "Office",
        "fabric": "Cotton Twill",
        "fabric_tag": "Stretch Twill",
        "image": "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=400&q=80",
    },
    {
        "item_id": "B03",
        "category": "Bottom",
        "item_name": "High-Waist Wide Trousers",
        "price": 1599.0,
        "rating": 4.9,
        "reviews": 140,
        "platform": "ZARA",
        "colour": "Black",
        "shade": "Obsidian",
        "style": "Formal",
        "occasion": "Interview",
        "fabric": "Rayon Blend",
        "fabric_tag": "Smooth Drape",
        "image": "https://images.unsplash.com/photo-1509551388413-e18d0ac5d495?auto=format&fit=crop&w=400&q=80",
    },
    {
        "item_id": "B04",
        "category": "Bottom",
        "item_name": "Pleated Ethnic Palazzo",
        "price": 899.0,
        "rating": 4.6,
        "reviews": 98,
        "platform": "FabIndia",
        "colour": "Off-White",
        "shade": "Ivory",
        "style": "Ethnic",
        "occasion": "Traditional Event",
        "fabric": "Silk Blend",
        "fabric_tag": "Light Silk",
        "image": "https://images.unsplash.com/photo-1583391733956-6c78276477e2?auto=format&fit=crop&w=400&q=80",
    },
    {
        "item_id": "B05",
        "category": "Bottom",
        "item_name": "Leather-Look Flare Pants",
        "price": 1899.0,
        "rating": 4.8,
        "reviews": 85,
        "platform": "H&M",
        "colour": "Dark Brown",
        "shade": "Chocolate",
        "style": "Trendy",
        "occasion": "Party",
        "fabric": "Faux Leather",
        "fabric_tag": "Sleek Finish",
        "image": "https://images.unsplash.com/photo-1551854838-212c50b4c184?auto=format&fit=crop&w=400&q=80",
    },

    # SHOES
    {
        "item_id": "S01",
        "category": "Shoes",
        "item_name": "Classic White Court Sneakers",
        "price": 1299.0,
        "rating": 4.9,
        "reviews": 610,
        "platform": "Adidas",
        "colour": "White",
        "shade": "Clean White",
        "style": "Casual",
        "occasion": "College",
        "fabric": "Leather Upper",
        "fabric_tag": "Easy Clean",
        "image": "https://images.unsplash.com/photo-1560769629-975ec94e6a86?auto=format&fit=crop&w=400&q=80",
    },
    {
        "item_id": "S02",
        "category": "Shoes",
        "item_name": "Penny Loafers",
        "price": 1799.0,
        "rating": 4.8,
        "reviews": 190,
        "platform": "Aldo",
        "colour": "Tan Brown",
        "shade": "Camel",
        "style": "Formal",
        "occasion": "Office",
        "fabric": "Genuine Leather",
        "fabric_tag": "Premium Leather",
        "image": "https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&w=400&q=80",
    },
    {
        "item_id": "S03",
        "category": "Shoes",
        "item_name": "Stiletto Ankle Strap Heels",
        "price": 1999.0,
        "rating": 4.7,
        "reviews": 115,
        "platform": "Mango",
        "colour": "Nude Pink",
        "shade": "Blush",
        "style": "Trendy",
        "occasion": "Party",
        "fabric": "Suede Finish",
        "fabric_tag": "Soft Suede",
        "image": "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=400&q=80",
    },
    {
        "item_id": "S04",
        "category": "Shoes",
        "item_name": "Embroidered Mojaris",
        "price": 999.0,
        "rating": 4.8,
        "reviews": 140,
        "platform": "Craftsvilla",
        "colour": "Gold & Maroon",
        "shade": "Gold",
        "style": "Ethnic",
        "occasion": "Traditional Event",
        "fabric": "Silk & Leather",
        "fabric_tag": "Handcrafted",
        "image": "https://images.unsplash.com/photo-1603808033192-082d6919d3e1?auto=format&fit=crop&w=400&q=80",
    },

    # ACCESSORIES
    {
        "item_id": "A01",
        "category": "Accessory",
        "item_name": "Minimalist Rose Gold Watch",
        "price": 699.0,
        "rating": 4.9,
        "reviews": 320,
        "platform": "Fossil",
        "colour": "Rose Gold",
        "shade": "Metallic",
        "style": "Minimal",
        "occasion": "Office",
        "fabric": "Stainless Steel",
        "fabric_tag": "Scratch Proof",
        "image": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=400&q=80",
    },
    {
        "item_id": "A02",
        "category": "Accessory",
        "item_name": "Canvas Daily Tote Bag",
        "price": 499.0,
        "rating": 4.7,
        "reviews": 280,
        "platform": "Myntra",
        "colour": "Off-White",
        "shade": "Natural",
        "style": "Casual",
        "occasion": "College",
        "fabric": "Organic Canvas",
        "fabric_tag": "Eco-Friendly",
        "image": "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=400&q=80",
    },
    {
        "item_id": "A03",
        "category": "Accessory",
        "item_name": "Structured Leather Handbag",
        "price": 1499.0,
        "rating": 4.8,
        "reviews": 150,
        "platform": "ZARA",
        "colour": "Deep Black",
        "shade": "Noir",
        "style": "Formal",
        "occasion": "Interview",
        "fabric": "Structured Leather",
        "fabric_tag": "Sleek Grain",
        "image": "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=400&q=80",
    },
    {
        "item_id": "A04",
        "category": "Accessory",
        "item_name": "Pearl Drop Statement Earrings",
        "price": 599.0,
        "rating": 4.8,
        "reviews": 210,
        "platform": "H&M",
        "colour": "Gold & Pearl",
        "shade": "Pearl",
        "style": "Trendy",
        "occasion": "Party",
        "fabric": "Alloy & Pearl",
        "fabric_tag": "Lightweight",
        "image": "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=400&q=80",
    },
]

DEMO_PALETTES: Dict[str, List[Dict[str, str]]] = {
    "Light": [
        {"name": "Navy Blue", "hex": "#1B2A47"},
        {"name": "Burgundy", "hex": "#6B1D2F"},
        {"name": "Forest Green", "hex": "#1E4731"},
        {"name": "Soft Ivory", "hex": "#F7F5EE"},
        {"name": "Dusty Lavender", "hex": "#B5A7D8"},
    ],
    "Medium": [
        {"name": "Deep Teal", "hex": "#114B5F"},
        {"name": "Olive Green", "hex": "#4E5B31"},
        {"name": "Warm Ochre", "hex": "#C7822A"},
        {"name": "Cream", "hex": "#F5EFEB"},
        {"name": "Rich Maroon", "hex": "#7A1C24"},
    ],
    "Tan": [
        {"name": "Rust Terracotta", "hex": "#B84A28"},
        {"name": "Sage Olive", "hex": "#5A6B4E"},
        {"name": "Camel Warm", "hex": "#C49A5A"},
        {"name": "Alabaster", "hex": "#F4EFEA"},
        {"name": "Deep Chocolate", "hex": "#3E251A"},
    ],
    "Deep": [
        {"name": "Pure White", "hex": "#FFFFFF"},
        {"name": "Cobalt Blue", "hex": "#164BB0"},
        {"name": "Emerald Green", "hex": "#0D6646"},
        {"name": "Vibrant Coral", "hex": "#E05A47"},
        {"name": "Royal Purple", "hex": "#4E2A84"},
    ],
}

DEMO_SUGGESTION_CHIPS = [
    "Comfortable",
    "Minimal",
    "Trendy",
    "Formal",
    "Budget Friendly",
    "More Colourful",
    "Simple",
    "Elegant",
    "Streetwear Vibe",
    "Breathable Linen",
]

DEMO_FABRIC_NOTES = {
    "Linen": "Ultra-breathable natural fiber that keeps you cool during warm college or casual days.",
    "Cotton Blend": "Wrinkle-resistant, crisp weave ideal for long office hours and formal settings.",
    "Denim": "Heavyweight, durable twill weave that molds to your body for timeless casual wear.",
    "Silk Satin": "Luxurious drape with subtle sheen, perfect for festive evening wear and parties.",
    "Rayon": "Silky-smooth flow with gentle drape for comfortable semi-formal trousers.",
    "Khadi Cotton": "Handwoven eco-friendly textile with organic texture, tailored for traditional events.",
    "Wool Blend": "Structured, insulating weave providing crisp lapels and sharp silhouette definition.",
}


def filter_demo_products(
    occasion: Optional[str] = None,
    style: Optional[str] = None,
    budget: float = 10000.0,
    favourite_colours: Optional[List[str]] = None,
) -> List[Dict]:
    filtered = []
    favourite_colours = [c.lower() for c in (favourite_colours or [])]

    for item in DEMO_PRODUCTS:
        # Budget check
        if item["price"] > budget:
            continue

        score = 0
        if occasion and item["occasion"].lower() == occasion.lower():
            score += 40
        if style and item["style"].lower() == style.lower():
            score += 30
        if any(c in item["colour"].lower() or c in item["shade"].lower() for c in favourite_colours):
            score += 30

        item_copy = {**item, "match_score": score}
        filtered.append(item_copy)

    filtered.sort(key=lambda x: (-x["match_score"], x["price"]))
    return filtered
